#!/bin/bash

# Скрипт для проверки Gateway, GatewayClass, ReferenceGrant и TLSRoute

echo "=========================================="
echo "Проверка GatewayClass"
echo "=========================================="
echo "GatewayClass:"
kubectl get gatewayclass || echo "⚠️  GatewayClass не найдены"
echo ""
echo "Описание GatewayClass envoy:"
kubectl describe gatewayclass envoy || echo "⚠️  GatewayClass envoy не найден"

echo ""
echo "=========================================="
echo "Проверка Gateway"
echo "=========================================="
echo "Gateways в namespace envoy-gateway:"
kubectl get gateway -n envoy-gateway || echo "⚠️  Namespace envoy-gateway не найден или Gateways отсутствуют"
echo ""
echo "Описание Gateway redis-gateway:"
kubectl describe gateway redis-gateway -n envoy-gateway || echo "⚠️  Gateway redis-gateway не найден"
echo ""
echo "Адрес Gateway:"
kubectl get gateway redis-gateway -n envoy-gateway -o jsonpath='{.status.addresses[*].value}' && echo || echo "⚠️  Адрес Gateway не назначен"
echo ""
echo "Services envoy-gateway:"
kubectl get svc -n envoy-gateway | grep envoy || echo "⚠️  Services envoy-gateway не найдены"
echo ""
echo "Примечание: Если Gateway был создан до ReferenceGrant, может потребоваться пересоздать Gateway:"
echo "  kubectl delete -f gateway.yaml && kubectl apply -f gateway.yaml"

echo ""
echo "=========================================="
echo "Проверка ReferenceGrant"
echo "=========================================="
echo "ReferenceGrants в namespace redis-standalone:"
kubectl get referencegrant -n redis-standalone || echo "⚠️  ReferenceGrants не найдены"
echo ""
echo "Описание ReferenceGrant allow-gateway-to-cert:"
kubectl describe referencegrant allow-gateway-to-cert -n redis-standalone || echo "⚠️  ReferenceGrant allow-gateway-to-cert не найден"

echo ""
echo "=========================================="
echo "Проверка TLSRoute"
echo "=========================================="
echo "TLSRoutes в namespace redis-standalone:"
kubectl get tlsroute -n redis-standalone || echo "⚠️  TLSRoutes не найдены"
echo ""
echo "Описание TLSRoute:"
kubectl describe tlsroute redis-cluster-1-route -n redis-standalone || echo "⚠️  TLSRoute redis-cluster-1-route не найден"
echo ""
echo "Статус TLSRoute:"
kubectl get tlsroute redis-cluster-1-route -n redis-standalone -o jsonpath='{.status.parents[*].conditions[*].type}' && echo || echo "⚠️  Не удалось получить статус TLSRoute"
echo ""
echo "Listeners Gateway:"
kubectl get gateway redis-gateway -n envoy-gateway -o yaml | grep -A 10 "listeners:" || echo "⚠️  Не удалось получить информацию о listeners"

echo ""
echo "=========================================="
echo "Проверка завершена"
echo "=========================================="
